use_frameworks!

target 'JKUBSAspects_Example' do
  pod 'JKUBSAspects', :path => '../'

  target 'JKUBSAspects_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
  pod 'FBSnapshotTestCase'
  end
end
